name: milligram
description: A porting of the Milligram CSS Framework for Dart.
version: 0.0.2
author: Gonzalo Chumillas <gchumillas@email.com>
homepage: https://github.com/gchumillas-dart/milligram

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
